### ISSUE TITLE
ModelKit Install w/updated measures

### ISSUE THREAD

**Issue by rogerkbaker** [sound-data/DEER-Prototypes-EnergyPlus#14]
One should clarify that, if Modelkit Catalyst is already installed, it may need to be uninstalled prior to installing Modelkit Caboodle. I had both versions and all rake commands kept referring back to the Catalyst version, which broke the rake process. Instructions are not clear that the new Modelkit must be installed if one already had the prior version.

**Comment by amine-lazrak** [comment]
Thank you for highlighting this issue. We've updated the README.md file with additional instructions to address this. Please feel free to review the changes and let us know if further modifications are required.
