### ISSUE TITLE
Question about timestep variable

### ISSUE THREAD

**Issue by rogerkbaker** [sound-data/DEER-Prototypes-EnergyPlus#15]
While testing the commercial models, I observed that the general.pxt file includes a parameter for timestep, with a default value of 4. While this is consistent with commercial CBECC and is sometimes recommended if timestep outputs need to align with 15-minute utility meter data, the EnergyPlus I/O Reference recommends 6 timesteps/hr minimum for HVAC simulations (See EnergyPlus V22.2 Input-Output Reference Manual, page number 45). Notwithstanding this distinction, it currently appears that any timestep defined in the global.pxt is being overridden by the "TIMESTEP=1" entry in the global.pxv file for commercial models. If I comment out the timestep in global.pxv, the "TIMESTEP=4" value from global.pxt is successfully used. I'd suggest that the global.pxv be modified to remove or comment out the TIMESTEP variable, unless these models are still being debugged.

**Comment by amine-lazrak** [comment]
Agreed. I have updated the timestep in all global.pxv files to align with EnergyPlus recommendations. Additionally, I have added it locally to gitignore to prevent it from being pushed to the remote repository when we use an hourly timestep to expedite model reviews.
