### ISSUE TITLE
Domestic hot water flow parameter

### ISSUE THREAD

**Issue by simularis** [sound-data/DEER-Prototypes-EnergyPlus#17]
When running the commercial prototype defaults, the domestic hot water systems don't show up in the composed IDF files. It appears to be due to a mismatch between parameter used in the prototype that is not part of the template.

The prototype has lines like this:

```ruby
  import "zoneloads/zonetemplate.pxt", :group => "classroom_class", :prefix => "classroom_class_" do
    ...
    parameter "dhw_flow_area", :default => 0.00015['GPM/ft2']
    parameter "dhw_water_heater_fuel", :default => "Gas"
    ...
  end
```

The template has lines like this:

```ruby
<% if dhw_flow > 0 %>
  ...
  WaterUse:Equipment,
    <%= zone_name %> DHW Equipment,  !- Name
    DHW,                     !- End-Use Subcategory
    <%= dhw_flow %>,  !- Peak Flow Rate {m3/s}
    ...
```

So, default models don't generate the DHW-related components within the IF clause.

**Comment by amine-lazrak** [comment]
Good catch. The parameter _dhw_flow_ is not defined in any root file, while _dhw_flow_area_ is not defined in the template. Your solution fixes the problem. Please see the comment on your PR. I'll merge it after the updates.
