### ISSUE TITLE
Challenges post-processing SFm, Ex

### ISSUE THREAD

**Issue by simularis** [sound-data/DEER-Prototypes-EnergyPlus#2]
I tried to reproduce SFm_Furnace_1975 and '85. The unexpected result was at the post-process stage, when some (SFm, Ex) rows ended up with mostly null results in the output despite having input data present.

Why? It seems that the output of "data transformation/SFm.py" (e.g. sfm_annual, etc.) is already labeled with vintages 'Ex' instead of 1975/1985 (confer Analysis/SFm_Furnace_1985/cohorts.csv). However, in residential post-process steps, weights tables have rows matching 1975 or 1985 but no rows matching 'Ex'. E.g.

- (R1,R2) "NumStor"."VintYear"
- (R3) "FloorArea_2022"."BldgVint"

Workaround: I was able to proceed by creating some rows for (SFm, Ex) in those two weights tables, based on 1975/1985. But wondering if there was another preferred solution.

**Comment by lyt5410** [comment]
I modified the SFm script to change BldgVint = 'Ex' into '1975' or '1985' based on the CZ. The SFm Ex prototypes were modelled such that if CZ is from 1 to 9, vintage is 1975, if CZ is from 10 to 16, vintage is 1985. I did some brief testing and it should allow the postgreSQL queries R1, R2, R3, R4 to run with no issues. P5 swaps the 1975/1985 back into 'Ex'. 

Please let me know if more issue arises.
