### ISSUE TITLE
Some simulations fail to run to completion

### ISSUE THREAD

**Issue by egamadniarb** [sound-data/DEER-Prototypes-EnergyPlus#4]
Running each simulation to establish a baseline and to verify reproducible results. In the single family prototypes ran into the following errors. Also ran into multiple errors in the mobile home prototypes not detailed here. The only modifications made where to change the keep flag to true in the global config, otherwise as supplied, multiple simulations do not run to completion without error.

Fully updated Windows 10
ModelKit and Energy Plus versions as in the readme
Python 3.11.2

#1: For SFm_Ceiling Insulation_1975

modelkit rake results in this error:

PS C:\DEER-Prototypes-EnergyPlus-2-15-2023\Analysis\SFm_Ceiling Insulation_1975> modelkit rake
Type Ctrl+C to cancel all tasks.
Evaluating worksheets...
Writing: CZ01/weather
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975/templates/root_ground_sp_ceiling.pxt" not found for row 2 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-HP/templates/root_ceiling.pxt" not found for row 3 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-NCEH/templates/root_ceiling.pxt" not found for row 4 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-NCGF/templates/root_ceiling.pxt" not found for row 5 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975/templates/root_ground_sp_ceiling.pxt" not found for row 6 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-HP/templates/root_ceiling.pxt" not found for row 7 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-NCEH/templates/root_ceiling.pxt" not found for row 8 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-NCGF/templates/root_ceiling.pxt" not found for row 9 of cohorts.csv
Writing: CZ02/weather
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975/templates/root_ground_sp_ceiling.pxt" not found for row 2 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-HP/templates/root_ceiling.pxt" not found for row 3 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-NCEH/templates/root_ceiling.pxt" not found for row 4 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-NCGF/templates/root_ceiling.pxt" not found for row 5 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975/templates/root_ground_sp_ceiling.pxt" not found for row 6 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-HP/templates/root_ceiling.pxt" not found for row 7 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-NCEH/templates/root_ceiling.pxt" not found for row 8 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-NCGF/templates/root_ceiling.pxt" not found for row 9 of cohorts.csv
Writing: CZ03/weather
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975/templates/root_ground_sp_ceiling.pxt" not found for row 2 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-HP/templates/root_ceiling.pxt" not found for row 3 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-NCEH/templates/root_ceiling.pxt" not found for row 4 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-NCGF/templates/root_ceiling.pxt" not found for row 5 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975/templates/root_ground_sp_ceiling.pxt" not found for row 6 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-HP/templates/root_ceiling.pxt" not found for row 7 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-NCEH/templates/root_ceiling.pxt" not found for row 8 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-NCGF/templates/root_ceiling.pxt" not found for row 9 of cohorts.csv
Writing: CZ04/weather
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975/templates/root_ground_sp_ceiling.pxt" not found for row 2 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-HP/templates/root_ceiling.pxt" not found for row 3 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-NCEH/templates/root_ceiling.pxt" not found for row 4 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-NCGF/templates/root_ceiling.pxt" not found for row 5 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975/templates/root_ground_sp_ceiling.pxt" not found for row 6 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-HP/templates/root_ceiling.pxt" not found for row 7 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-NCEH/templates/root_ceiling.pxt" not found for row 8 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-NCGF/templates/root_ceiling.pxt" not found for row 9 of cohorts.csv
Writing: CZ05/weather
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975/templates/root_ground_sp_ceiling.pxt" not found for row 2 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-HP/templates/root_ceiling.pxt" not found for row 3 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-NCEH/templates/root_ceiling.pxt" not found for row 4 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-NCGF/templates/root_ceiling.pxt" not found for row 5 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975/templates/root_ground_sp_ceiling.pxt" not found for row 6 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-HP/templates/root_ceiling.pxt" not found for row 7 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-NCEH/templates/root_ceiling.pxt" not found for row 8 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-NCGF/templates/root_ceiling.pxt" not found for row 9 of cohorts.csv
Writing: CZ06/weather
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975/templates/root_ground_sp_ceiling.pxt" not found for row 2 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-HP/templates/root_ceiling.pxt" not found for row 3 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-NCEH/templates/root_ceiling.pxt" not found for row 4 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-NCGF/templates/root_ceiling.pxt" not found for row 5 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975/templates/root_ground_sp_ceiling.pxt" not found for row 6 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-HP/templates/root_ceiling.pxt" not found for row 7 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-NCEH/templates/root_ceiling.pxt" not found for row 8 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-NCGF/templates/root_ceiling.pxt" not found for row 9 of cohorts.csv
Writing: CZ07/weather
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975/templates/root_ground_sp_ceiling.pxt" not found for row 2 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-HP/templates/root_ceiling.pxt" not found for row 3 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-NCEH/templates/root_ceiling.pxt" not found for row 4 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-NCGF/templates/root_ceiling.pxt" not found for row 5 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975/templates/root_ground_sp_ceiling.pxt" not found for row 6 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-HP/templates/root_ceiling.pxt" not found for row 7 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-NCEH/templates/root_ceiling.pxt" not found for row 8 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-NCGF/templates/root_ceiling.pxt" not found for row 9 of cohorts.csv
Writing: CZ08/weather
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975/templates/root_ground_sp_ceiling.pxt" not found for row 2 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-HP/templates/root_ceiling.pxt" not found for row 3 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-NCEH/templates/root_ceiling.pxt" not found for row 4 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-NCGF/templates/root_ceiling.pxt" not found for row 5 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975/templates/root_ground_sp_ceiling.pxt" not found for row 6 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-HP/templates/root_ceiling.pxt" not found for row 7 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-NCEH/templates/root_ceiling.pxt" not found for row 8 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-NCGF/templates/root_ceiling.pxt" not found for row 9 of cohorts.csv
Writing: CZ09/weather
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975/templates/root_ground_sp_ceiling.pxt" not found for row 2 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-HP/templates/root_ceiling.pxt" not found for row 3 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-NCEH/templates/root_ceiling.pxt" not found for row 4 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-1 Story-1975-NCGF/templates/root_ceiling.pxt" not found for row 5 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975/templates/root_ground_sp_ceiling.pxt" not found for row 6 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-HP/templates/root_ceiling.pxt" not found for row 7 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-NCEH/templates/root_ceiling.pxt" not found for row 8 of cohorts.csv
Root template "C:/DEER-Prototypes-EnergyPlus-2-15-2023/prototypes/residential/SFm-2 Story-1975-NCGF/templates/root_ceiling.pxt" not found for row 9 of cohorts.csv
Processing: results-profile-gas.csv
Processing: results-summary.csv
Processing: results-profile-elec.csv
Elapsed task duration: 0.007999 sec
PS C:\DEER-Prototypes-EnergyPlus-2-15-2023\Analysis\SFm_Ceiling Insulation_1975>

#2 SFm_Ceiling Insulation_1985 has the issue.

Those templates exist but without the '_ceiling' suffix.

#3 SFm_SEER Rated AC_HP_1985

modelkit rake results in:

PS C:\DEER-Prototypes-EnergyPlus-2-15-2023\Analysis\SFm_SEER Rated AC_HP_1985> modelkit rake
Type Ctrl+C to cancel all tasks.
Evaluating worksheets...
Writing: CZ10/weather
Cases worksheet "cases/SFm_1_rDXHP_Ex_dxHP_equip__spltHP-SEER-BA.csv" not found for row 2 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXHP_Ex_dxHP_equip__spltHP-SEER-BA.csv" not found for row 3 of cohorts.csv
Cases worksheet "cases/SFm_1_rDXGF_Ex_dxAC_equip__pkgSEER-BA.csv" not found for row 4 of cohorts.csv
Cases worksheet "cases/SFm_1_rDXGF_Ex_dxAC_equip__spltSEER-BA.csv" not found for row 5 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXGF_Ex_dxAC_equip__pkgSEER-BA.csv" not found for row 6 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXGF_Ex_dxAC_equip__spltSEER-BA.csv" not found for row 7 of cohorts.csv
Writing: CZ11/weather
Cases worksheet "cases/SFm_1_rDXHP_Ex_dxHP_equip__spltHP-SEER-BA.csv" not found for row 2 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXHP_Ex_dxHP_equip__spltHP-SEER-BA.csv" not found for row 3 of cohorts.csv
Cases worksheet "cases/SFm_1_rDXGF_Ex_dxAC_equip__pkgSEER-BA.csv" not found for row 4 of cohorts.csv
Cases worksheet "cases/SFm_1_rDXGF_Ex_dxAC_equip__spltSEER-BA.csv" not found for row 5 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXGF_Ex_dxAC_equip__pkgSEER-BA.csv" not found for row 6 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXGF_Ex_dxAC_equip__spltSEER-BA.csv" not found for row 7 of cohorts.csv
Writing: CZ12/weather
Cases worksheet "cases/SFm_1_rDXHP_Ex_dxHP_equip__spltHP-SEER-BA.csv" not found for row 2 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXHP_Ex_dxHP_equip__spltHP-SEER-BA.csv" not found for row 3 of cohorts.csv
Cases worksheet "cases/SFm_1_rDXGF_Ex_dxAC_equip__pkgSEER-BA.csv" not found for row 4 of cohorts.csv
Cases worksheet "cases/SFm_1_rDXGF_Ex_dxAC_equip__spltSEER-BA.csv" not found for row 5 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXGF_Ex_dxAC_equip__pkgSEER-BA.csv" not found for row 6 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXGF_Ex_dxAC_equip__spltSEER-BA.csv" not found for row 7 of cohorts.csv
Writing: CZ13/weather
Cases worksheet "cases/SFm_1_rDXHP_Ex_dxHP_equip__spltHP-SEER-BA.csv" not found for row 2 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXHP_Ex_dxHP_equip__spltHP-SEER-BA.csv" not found for row 3 of cohorts.csv
Cases worksheet "cases/SFm_1_rDXGF_Ex_dxAC_equip__pkgSEER-BA.csv" not found for row 4 of cohorts.csv
Cases worksheet "cases/SFm_1_rDXGF_Ex_dxAC_equip__spltSEER-BA.csv" not found for row 5 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXGF_Ex_dxAC_equip__pkgSEER-BA.csv" not found for row 6 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXGF_Ex_dxAC_equip__spltSEER-BA.csv" not found for row 7 of cohorts.csv
Writing: CZ14/weather
Cases worksheet "cases/SFm_1_rDXHP_Ex_dxHP_equip__spltHP-SEER-BA.csv" not found for row 2 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXHP_Ex_dxHP_equip__spltHP-SEER-BA.csv" not found for row 3 of cohorts.csv
Cases worksheet "cases/SFm_1_rDXGF_Ex_dxAC_equip__pkgSEER-BA.csv" not found for row 4 of cohorts.csv
Cases worksheet "cases/SFm_1_rDXGF_Ex_dxAC_equip__spltSEER-BA.csv" not found for row 5 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXGF_Ex_dxAC_equip__pkgSEER-BA.csv" not found for row 6 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXGF_Ex_dxAC_equip__spltSEER-BA.csv" not found for row 7 of cohorts.csv
Writing: CZ15/weather
Cases worksheet "cases/SFm_1_rDXHP_Ex_dxHP_equip__spltHP-SEER-BA.csv" not found for row 2 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXHP_Ex_dxHP_equip__spltHP-SEER-BA.csv" not found for row 3 of cohorts.csv
Cases worksheet "cases/SFm_1_rDXGF_Ex_dxAC_equip__pkgSEER-BA.csv" not found for row 4 of cohorts.csv
Cases worksheet "cases/SFm_1_rDXGF_Ex_dxAC_equip__spltSEER-BA.csv" not found for row 5 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXGF_Ex_dxAC_equip__pkgSEER-BA.csv" not found for row 6 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXGF_Ex_dxAC_equip__spltSEER-BA.csv" not found for row 7 of cohorts.csv
Writing: CZ16/weather
Cases worksheet "cases/SFm_1_rDXHP_Ex_dxHP_equip__spltHP-SEER-BA.csv" not found for row 2 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXHP_Ex_dxHP_equip__spltHP-SEER-BA.csv" not found for row 3 of cohorts.csv
Cases worksheet "cases/SFm_1_rDXGF_Ex_dxAC_equip__pkgSEER-BA.csv" not found for row 4 of cohorts.csv
Cases worksheet "cases/SFm_1_rDXGF_Ex_dxAC_equip__spltSEER-BA.csv" not found for row 5 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXGF_Ex_dxAC_equip__pkgSEER-BA.csv" not found for row 6 of cohorts.csv
Cases worksheet "cases/SFm_2_rDXGF_Ex_dxAC_equip__spltSEER-BA.csv" not found for row 7 of cohorts.csv
Processing: results-profile-gas.csv
Processing: results-summary.csv
Processing: results-profile-elec.csv
Elapsed task duration: 0.0 sec
PS C:\DEER-Prototypes-EnergyPlus-2-15-2023\Analysis\SFm_SEER Rated AC_HP_1985>

#4 SFm_SEER_Rated_AC_HP_New has the same issue

The 1975 scripts run fine.

#5 and 6 SFm_Brushless_Fan_Motor_1975/1985

modelkit rake fails with the following:

Generating: CZ08/site.pxt
Composing: CZ08/SFm&1&rDXGF&Ex&HV_AirDist__SupFanMtr-BA/RE-HV-PSCFanMotor/instance.idf
Composing: CZ08/SFm&1&rDXGF&Ex&HV_AirDist__SupFanMtr-BA/RE-HV-BrushlessFanMotor/instance.idf
Running: CZ08/SFm&1&rDXGF&Ex&HV_AirDist__SupFanMtr-BA/RE-HV-BrushlessFanMotor/instance.idf
Running: CZ08/SFm&1&rDXGF&Ex&HV_AirDist__SupFanMtr-BA/RE-HV-PSCFanMotor/instance.idf
Composing: CZ09/SFm&1&rDXGF&Ex&HV_AirDist__SupFanMtr-BA/RE-HV-BrushlessFanMotor/instance.idf
Running: CZ09/SFm&1&rDXGF&Ex&HV_AirDist__SupFanMtr-BA/RE-HV-BrushlessFanMotor/instance.idf
Composing: CZ08/SFm&2&rDXGF&Ex&HV_AirDist__SupFanMtr-BA/RE-HV-PSCFanMotor/instance.idf
Running: CZ08/SFm&2&rDXGF&Ex&HV_AirDist__SupFanMtr-BA/RE-HV-PSCFanMotor/instance.idf
Composing: CZ08/SFm&2&rDXGF&Ex&HV_AirDist__SupFanMtr-BA/RE-HV-BrushlessFanMotor/instance.idf
Running: CZ08/SFm&2&rDXGF&Ex&HV_AirDist__SupFanMtr-BA/RE-HV-BrushlessFanMotor/instance.idf
Composing: CZ09/SFm&1&rDXGF&Ex&HV_AirDist__SupFanMtr-BA/RE-HV-PSCFanMotor/instance.idf
Running: CZ09/SFm&1&rDXGF&Ex&HV_AirDist__SupFanMtr-BA/RE-HV-PSCFanMotor/instance.idf
Processing: results-profile-gas.csv
Processing: results-summary.csv
Processing: results-profile-elec.csv
rake aborted!
IndexError: element size differs (8977 should be 8809)
C:/DEER-Prototypes-EnergyPlus-jwj/Analysis/SFm_Brushless_Fan_Motor_1975/rakefile.rb:780:in `transpose'
C:/DEER-Prototypes-EnergyPlus-jwj/Analysis/SFm_Brushless_Fan_Motor_1975/rakefile.rb:780:in `block in aggregate_profiles'
C:/DEER-Prototypes-EnergyPlus-jwj/Analysis/SFm_Brushless_Fan_Motor_1975/rakefile.rb:779:in `open'
C:/DEER-Prototypes-EnergyPlus-jwj/Analysis/SFm_Brushless_Fan_Motor_1975/rakefile.rb:779:in `aggregate_profiles'
C:/DEER-Prototypes-EnergyPlus-jwj/Analysis/SFm_Brushless_Fan_Motor_1975/rakefile.rb:742:in `block in <top (required)>'
C:/Program Files (x86)/Modelkit Catalyst/lib/rubygems/gems/modelkit-0.8.1/lib/modelkit/cli.rb:348:in `block (2 levels) in <module:CLI>'
C:/Program Files (x86)/Modelkit Catalyst/vendor/rubygems/gems/gli-2.13.2/lib/gli/command_support.rb:126:in `call'
C:/Program Files (x86)/Modelkit Catalyst/vendor/rubygems/gems/gli-2.13.2/lib/gli/command_support.rb:126:in `execute'
C:/Program Files (x86)/Modelkit Catalyst/vendor/rubygems/gems/gli-2.13.2/lib/gli/app_support.rb:296:in `block in call_command'
C:/Program Files (x86)/Modelkit Catalyst/vendor/rubygems/gems/gli-2.13.2/lib/gli/app_support.rb:309:in `call'
C:/Program Files (x86)/Modelkit Catalyst/vendor/rubygems/gems/gli-2.13.2/lib/gli/app_support.rb:309:in `call_command'
C:/Program Files (x86)/Modelkit Catalyst/vendor/rubygems/gems/gli-2.13.2/lib/gli/app_support.rb:83:in `run'
C:/Program Files (x86)/Modelkit Catalyst/bin/../lib/rubygems/gems/modelkit-0.8.1/bin/modelkit:3:in `<main>'
Tasks: TOP => default => results => C:/DEER-Prototypes-EnergyPlus-jwj/Analysis/SFm_Brushless_Fan_Motor_1975/results-profile-gas.csv
(See full trace by running task with --trace)
error: exit
Elapsed task duration: 531.090215 sec
PS C:\DEER-Prototypes-EnergyPlus-jwj\Analysis\SFm_Brushless_Fan_Motor_1975>

**Comment by lyt5410** [comment]
Thanks for raising this issue. 
I fixed the following measures, these should work now (cohort.csv now points to the correct root files):

- SFm_Ceiling Insulation_1975
- SFm_Ceiling Insulation_1985 

We are looking into the issue with the following measures:

- SFm_SEER Rated AC_HP_1985
- SFm_SEER Rated AC_HP_New

As for the SFm_Brushless_Fan_Motor_1975/1985, despite the rake being aborted, it seems that the file "Results_summary.csv" is generated properly, as does each individual models. lease let me know if that's not the case. This rake error seem to be only associated with the file "results-profile-elec.csv" which is not needed for the subsequent processes. We are looking into the rake error.

**Comment by egamadniarb** [comment]
Thank you!

**Comment by lyt5410** [comment]
We just pushed fixes to the SEER Rated ACHP cohort files. Both of these should work now.
- SFm_SEER Rated AC_HP_1985
- SFm_SEER Rated AC_HP_New
Please let us know if there are more bugs/errors.
