### ISSUE TITLE
Commercial:Code: Typo in T24_2025_new.csv

### ISSUE THREAD

**Issue by netzero2020** [sound-data/DEER-Prototypes-EnergyPlus#51]
There is a typo in the [Opaque Envelope table.](table:   Opaque Envelope Requirements) . U-factor for Roofs | Metal Buildings is entered as 0.38. It should be 0.038.
<img width="434" alt="Commercial MetalBuilding Roof Typo" src="https://github.com/sound-data/DEER-Prototypes-EnergyPlus/assets/56174983/87e2d05f-c3a0-485c-aaad-4aaebd18442c">

**Comment by mmlx1215** [comment]
U factor of Roofs | Metal Buildings is updated to 0.038. @netzero2020
