### ISSUE TITLE
Output:Meter: invalid Key Name="GAS:FACILITY"

### ISSUE THREAD

**Issue by simularis** [sound-data/DEER-Prototypes-EnergyPlus#6]
**Description**: EnergyPlus issues an error message for the hourly report object.

```Output:Meter: invalid Key Name="GAS:FACILITY" - not found.```

**Example in source code**:

https://github.com/sound-data/DEER-Prototypes-EnergyPlus/blob/fc185f6843b2ef6c836d5caa6a1bfaeb3f13647c/prototypes/residential/DMo/templates/root.pxt#L7915

This syntax seems to be present in all the residential templates.

**Suggested fix**: per [Output:Meter documentation](https://bigladdersoftware.com/epx/docs/9-5/input-output-reference/input-for-output.html#outputmeter-and-outputmetermeterfileonly), change `Gas` to `NaturalGas` or comment out the hourly gas report if not needed.

**Comment by lyt5410** [comment]
ok I have made 3 separate commits, one for each building type to fix this error (changed output:meter syntax from Gas to NaturalGas). Let me know if any similar error still occurs.

**Comment by egamadniarb** [comment]
The latest commits have caused regressions.

One of many examples is included below. I have not tested all measures but it appears that these changes have broken most if not all measures.

Reverting the 3 commits allows the measures to be run.  

For measure MFm_Furnace errors:

Error: Undefined parameter specified (timestep); parameter ignored.
Error: Undefined parameter specified (run_control); parameter ignored.
Error: Undefined parameter specified (run_name); parameter ignored.
Error: Undefined parameter specified (glass_u); parameter ignored.
Error: Undefined parameter specified (glass_shgc); parameter ignored.
Error: Undefined parameter specified (wall_consol_layer_thickness); parameter ignored.
Error: Undefined parameter specified (wall_consol_layer_conductivity); parameter ignored.
Error: Undefined parameter specified (ceil_consol_layer_thickness); parameter ignored.
Error: Undefined parameter specified (ceil_consol_layer_conductivity); parameter ignored.
Error: Undefined parameter specified (heating_sch_DEER_mrn); parameter ignored.
Error: Undefined parameter specified (heating_sch_DEER_day); parameter ignored.
Error: Undefined parameter specified (heating_sch_DEER_eve); parameter ignored.
Error: Undefined parameter specified (heating_sch_DEER_nit); parameter ignored.
Error: Undefined parameter specified (cooling_sch_DEER_mrn); parameter ignored.
Error: Undefined parameter specified (cooling_sch_DEER_day); parameter ignored.
Error: Undefined parameter specified (cooling_sch_DEER_eve); parameter ignored.
Error: Undefined parameter specified (cooling_sch_DEER_nit); parameter ignored.
Error: Undefined parameter specified (timestep); parameter ignored.
Error: Undefined parameter specified (run_control); parameter ignored.
Error: Undefined parameter specified (run_name); parameter ignored.
Error: Undefined parameter specified (glass_u); parameter ignored.
Error: Undefined parameter specified (glass_shgc); parameter ignored.
Error: Undefined parameter specified (wall_consol_layer_thickness); parameter ignored.
Error: Undefined parameter specified (wall_consol_layer_conductivity); parameter ignored.
Error: Undefined parameter specified (ceil_consol_layer_thickness); parameter ignored.
Error: Undefined parameter specified (ceil_consol_layer_conductivity); parameter ignored.
Error: Undefined parameter specified (heating_sch_DEER_mrn); parameter ignored.
Error: Undefined parameter specified (heating_sch_DEER_day); parameter ignored.
Error: Undefined parameter specified (heating_sch_DEER_eve); parameter ignored.
Error: Undefined parameter specified (heating_sch_DEER_nit); parameter ignored.
Error: Undefined parameter specified (cooling_sch_DEER_mrn); parameter ignored.
Error: Undefined parameter specified (cooling_sch_DEER_day); parameter ignored.
Error: Undefined parameter specified (cooling_sch_DEER_eve); parameter ignored.
Error: Undefined parameter specified (cooling_sch_DEER_nit); parameter ignored.
Error: Undefined parameter specified (climate_zone); parameter ignored.
Error: Undefined parameter specified (infiltration_ACH); parameter ignored.
Error: Undefined parameter specified (climate_zone); parameter ignored.
Error: Undefined parameter specified (infiltration_ACH); parameter ignored.
Error: Undefined parameter specified (total_leakage_ratio); parameter ignored.
Error: Undefined parameter specified (shading_control); parameter ignored.
Error: Undefined parameter specified (burner_eff); parameter ignored.
Error: Undefined parameter specified (supplyfan_total_eff); parameter ignored.
Error: Undefined parameter specified (motor_eff); parameter ignored.
Error: Undefined parameter specified (timestep); parameter ignored.
Error: Undefined parameter specified (run_control); parameter ignored.
Error: Undefined parameter specified (run_name); parameter ignored.
Error: Undefined parameter specified (total_leakage_ratio); parameter ignored.
Error: Undefined parameter specified (shading_control); parameter ignored.
Error: Undefined parameter specified (burner_eff); parameter ignored.
Error: Undefined parameter specified (supplyfan_total_eff); parameter ignored.
Error: Undefined parameter specified (motor_eff); parameter ignored.
NameError: undefined local variable or method `heating_sch_DEER_day' for #<Modelkit::Parametrics::TemplateScope:0x93d5210>
c:/EnergyModels/Latest/DEER-Prototypes-EnergyPlus/prototypes/residential/MFm-1985/templates/root.pxt:90:in `__binding__'

**Comment by simularis** [comment]
@egamadniarb Did you have any errors with DMo or SFm?

The commit for MFm (01854fc) had an extra change, on first line of the file, that breaks that template.

```diff
-------------- prototypes/residential/MFm-1985/templates/root.pxt --------------
index 7ebbd95..7e4ee48 100644
@@ -1,4 +1,4 @@
-<%#INTERFACE
+Output:Meter,NaturalGas<%#INTERFACE
```

**Comment by lyt5410** [comment]
Thanks both for pointing this out. I fixed the typo on MFm-1985 on the repo.
